CMDS = {"SEND_SIGNATURE": 0x81,
        "SEND_RAW_SENSOR_VALUES": 0x86,
        "SEND_TRIMPOT": 0xB0,
        "SEND_BATTERY_MILLIVOLTS": 0xB1,
        "DO_PLAY": 0xB3,
        "PI_CALIBRATE": 0xB4,
        "DO_CLEAR": 0xB7,
        "DO_PRINT": 0xB8,
        "DO_LCD_GOTO_XY": 0xB9,
        "LINE_SENSORS_RESET_CALIBRATION": 0xB5,
        "SEND_LINE_POSITION": 0xB6,
        "AUTO_CALIBRATE": 0xBA,
        "SET_PID": 0xBB,
        "STOP_PID": 0xBC,
        "M1_FORWARD": 0xC1,
        "M1_BACKWARD": 0xC2,
        "M2_FORWARD": 0xC5,
        "M2_BACKWARD": 0xC6
        }
